# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "rice", ">=1.4.2"

gem "rdoc", "~>3.10", :group => [:development, :test]
gem "rake-compiler", ">=0", :group => [:development, :test]
gem "chunky_png", ">=0", :group => [:development, :test]
gem "hoe", "~>3.5", :group => [:development, :test]

# vim: syntax=ruby
