=begin 
 ******************************************************************************
 * 
 * Copyright (C) 2011 Elliot Laster
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 ******************************************************************************
=end

# Compile with Rice rather than straight mkmf
require 'rubygems'
require 'mkmf-rice'

# Add the arguments to the linker flags.
def append_ld_flags(flags) 
  flags = [flags] unless flags.is_a?(Array)
  with_ldflags("#{$LDFLAGS} #{flags.join(' ')}") { true }
end

# Check for mapnik-config
if %x{which mapnik-config}.length == 0
  abort("\n***\n mapnik-config is missing!\n Is mapnik2 installed?\n Is mapnik-config in your $PATH?\n***\n\n")
end

LIBDIR = Config::CONFIG['libdir']
INCLUDEDIR = Config::CONFIG['includedir'] 

$LDFLAGS += " -lmapnik2 "
$CFLAGS += %x{mapnik-config --cflags}

#------------------------------------------------------------------------------#
# Ruby-Mapnik configuration
# 
# Creates a ruby file with the constants for the input and font paths.
#------------------------------------------------------------------------------#
input_plugin_path = %x{mapnik-config --input-plugins}.chomp
font_path = %x{mapnik-config --fonts}.chomp
ruby_mapnik_config = <<-EOF
# This file is generated by extconf.rb DO NOT MODIFY!
module Mapnik
  INPUT_PLUGIN_PATH = '#{input_plugin_path}'
  FONT_PATH = '#{font_path}'
end
EOF

mapnik_config_file_path = File.join(File.expand_path(File.dirname(__FILE__)), '..', '..', 'lib', 'ruby_mapnik_config.rb')
FileUtils.rm(mapnik_config_file_path) if File.exists?(mapnik_config_file_path)
File.open(mapnik_config_file_path, 'w+') do |file|  
  file.write(ruby_mapnik_config)
end


if RUBY_PLATFORM =~ /darwin/
    # In order to link the shared library into our bundle with GCC 4.x on OSX, we have to work around a bug:
    #   GCC redefines symbols - which the -fno-common prohibits.  In order to keep the -fno-common, we
    #   remove the flat_namespace (we now have two namespaces, which fixes the GCC clash).  Also, we now lookup
    #   symbols in both the namespaces (dynamic_lookup).
    
    $LDSHARED_CXX.gsub!('suppress', 'dynamic_lookup')
    $LDSHARED_CXX.gsub!('-flat_namespace', '')
    
    append_ld_flags '-all_load'
end

create_makefile("ruby_mapnik")
